name: Auto Pull on Remote Machine

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan  >> ~/.ssh/known_hosts

    - name: Pull code on remote server
      run: ssh -i ~/.ssh/id_rsa forger@34.16.177.159 "cd /forger/ && git pull"
